import { Roboto } from "next/font/google";
import "./globals.css";
import Header from ".//components/layout/Header";
import {AppProvider} from ".//components/AppContext";
import {Toaster} from "react-hot-toast";


const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })


export const metadata = {
  title: "App-etite | food ordering app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
      <AppProvider>
      <Toaster />
        <main>        
              {children}
        </main>
      </AppProvider>
      </body>
    </html>
  );
}
